<?xml version="1.0" encoding="utf-8"?><Database Name="PersonnelManagement" Class="PersonnelManagementDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-PNFFHRG1\MSSQLSERVER01;Initial Catalog=PersonnelManagement;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="PersonnelManagementConnectionString5" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChamCong" Member="ChamCongs">
    <Type Name="ChamCong">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayChamCong" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GioRa" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="GioVao" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="idNhanVien" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_ChamCong" Member="NhanVien" ThisKey="idNhanVien" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UngVien" Member="UngViens">
    <Type Name="UngVien">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenNhanVien" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="que" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gioiTinh" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="duongDanCV" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="idChucVuUngTuyen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idTuyenDung" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngayUngTuyen" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="daXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ChucVu_UngVien" Member="ChucVu" ThisKey="idChucVuUngTuyen" OtherKey="id" Type="ChucVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietLuong" Member="ChiTietLuongs">
    <Type Name="ChiTietLuong">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ngayNhanLuong" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="luongTruocKhauTru" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="luongSauKhauTru" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="tongKhauTru" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="tongPhuCap" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="tongKhenThuong" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="tongTienPhat" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="idNhanVien" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="idKyLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="capNhatLuong" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="KyLuong_ChiTietLuong" Member="KyLuong" ThisKey="idKyLuong" OtherKey="id" Type="KyLuong" IsForeignKey="true" />
      <Association Name="NhanVien_ChiTietLuong" Member="NhanVien" ThisKey="idNhanVien" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChucVu" Member="ChucVus">
    <Type Name="ChucVu">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChucVu" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="luongCoBan" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="tyLeHoaHong" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="moTa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="idPhongBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ChucVu_UngVien" Member="UngViens" ThisKey="id" OtherKey="idChucVuUngTuyen" Type="UngVien" />
      <Association Name="ChucVu_NhanVien" Member="NhanViens" ThisKey="id" OtherKey="idChucVu" Type="NhanVien" />
      <Association Name="ChucVu_TuyenDung" Member="TuyenDungs" ThisKey="id" OtherKey="idChucVu" Type="TuyenDung" />
      <Association Name="PhongBan_ChucVu" Member="PhongBan" ThisKey="idPhongBan" OtherKey="id" Type="PhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhGiaNhanVien" Member="DanhGiaNhanViens">
    <Type Name="DanhGiaNhanVien">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiemSo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiemChuyenCan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiemNangLuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NhanXet" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idNhanVien" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="idNguoiDanhGia" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_DanhGiaNhanVien" Member="NhanVien" ThisKey="idNhanVien" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
      <Association Name="NhanVien_DanhGiaNhanVien1" Member="NhanVien1" ThisKey="idNguoiDanhGia" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HopDongLaoDong" Member="HopDongLaoDongs">
    <Type Name="HopDongLaoDong">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoaiHopDong" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NgayKy" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Luong" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="idNhanVien" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="NhanVien_HopDongLaoDong" Member="NhanVien" ThisKey="idNhanVien" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhauTru" Member="KhauTrus">
    <Type Name="KhauTru">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="loaiKhauTru" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soTien" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="moTa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="idNguoiTao" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="KhauTru_NhanVien_KhauTru" Member="NhanVien_KhauTrus" ThisKey="id" OtherKey="idKhauTru" Type="NhanVien_KhauTru" />
      <Association Name="NhanVien_KhauTru" Member="NhanVien" ThisKey="idNguoiTao" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KyLuong" Member="KyLuongs">
    <Type Name="KyLuong">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ngayBatDau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngayChiTra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="KyLuong_ChiTietLuong" Member="ChiTietLuongs" ThisKey="id" OtherKey="idKyLuong" Type="ChiTietLuong" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Que" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AnhDaiDien" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="idChucVu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPhongBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoaiNhanVien" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DaXoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_ChamCong" Member="ChamCongs" ThisKey="id" OtherKey="idNhanVien" Type="ChamCong" />
      <Association Name="NhanVien_ChiTietLuong" Member="ChiTietLuongs" ThisKey="id" OtherKey="idNhanVien" Type="ChiTietLuong" />
      <Association Name="NhanVien_DanhGiaNhanVien" Member="DanhGiaNhanViens" ThisKey="id" OtherKey="idNhanVien" Type="DanhGiaNhanVien" />
      <Association Name="NhanVien_DanhGiaNhanVien1" Member="DanhGiaNhanViens1" ThisKey="id" OtherKey="idNguoiDanhGia" Type="DanhGiaNhanVien" />
      <Association Name="NhanVien_HopDongLaoDong" Member="HopDongLaoDongs" ThisKey="id" OtherKey="idNhanVien" Type="HopDongLaoDong" />
      <Association Name="NhanVien_KhauTru" Member="KhauTrus" ThisKey="id" OtherKey="idNguoiTao" Type="KhauTru" />
      <Association Name="NhanVien_NhanVien_KhauTru" Member="NhanVien_KhauTrus" ThisKey="id" OtherKey="idNhanVien" Type="NhanVien_KhauTru" />
      <Association Name="NhanVien_NhanVien_PhuCap" Member="NhanVien_PhuCaps" ThisKey="id" OtherKey="idNhanVien" Type="NhanVien_PhuCap" />
      <Association Name="NhanVien_NhanVien_ThuongPhat" Member="NhanVien_ThuongPhats" ThisKey="id" OtherKey="idNhanVien" Type="NhanVien_ThuongPhat" />
      <Association Name="NhanVien_TaiKhoan" Member="TaiKhoans" ThisKey="id" OtherKey="idNhanVien" Type="TaiKhoan" />
      <Association Name="NhanVien_ThuongPhat" Member="ThuongPhats" ThisKey="id" OtherKey="idNguoiTao" Type="ThuongPhat" />
      <Association Name="NhanVien_TuyenDung" Member="TuyenDungs" ThisKey="id" OtherKey="idNguoiTao" Type="TuyenDung" />
      <Association Name="NhanVien_NghiPhep" Member="NghiPheps" ThisKey="id" OtherKey="idNhanVien" Type="NghiPhep" />
      <Association Name="ChucVu_NhanVien" Member="ChucVu" ThisKey="idChucVu" OtherKey="id" Type="ChucVu" IsForeignKey="true" />
      <Association Name="PhongBan_NhanVien" Member="PhongBan" ThisKey="idPhongBan" OtherKey="id" Type="PhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien_KhauTru" Member="NhanVien_KhauTrus">
    <Type Name="NhanVien_KhauTru">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idNhanVien" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="idKhauTru" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thangApDung" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="KhauTru_NhanVien_KhauTru" Member="KhauTru" ThisKey="idKhauTru" OtherKey="id" Type="KhauTru" IsForeignKey="true" />
      <Association Name="NhanVien_NhanVien_KhauTru" Member="NhanVien" ThisKey="idNhanVien" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien_PhuCap" Member="NhanVien_PhuCaps">
    <Type Name="NhanVien_PhuCap">
      <Column Name="idNhanVien" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idPhuCap" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_NhanVien_PhuCap" Member="NhanVien" ThisKey="idNhanVien" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
      <Association Name="PhuCap_NhanVien_PhuCap" Member="PhuCap" ThisKey="idPhuCap" OtherKey="id" Type="PhuCap" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien_ThuongPhat" Member="NhanVien_ThuongPhats">
    <Type Name="NhanVien_ThuongPhat">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idNhanVien" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="idThuongPhat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="thangApDung" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NhanVien_NhanVien_ThuongPhat" Member="NhanVien" ThisKey="idNhanVien" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
      <Association Name="ThuongPhat_NhanVien_ThuongPhat" Member="ThuongPhat" ThisKey="idThuongPhat" OtherKey="id" Type="ThuongPhat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhongBan" Member="PhongBans">
    <Type Name="PhongBan">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhongBan" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="PhongBan_ChucVu" Member="ChucVus" ThisKey="id" OtherKey="idPhongBan" Type="ChucVu" />
      <Association Name="PhongBan_NhanVien" Member="NhanViens" ThisKey="id" OtherKey="idPhongBan" Type="NhanVien" />
      <Association Name="PhongBan_TuyenDung" Member="TuyenDungs" ThisKey="id" OtherKey="idPhongBan" Type="TuyenDung" />
    </Type>
  </Table>
  <Table Name="dbo.PhuCap" Member="PhuCaps">
    <Type Name="PhuCap">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="soTien" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="lyDoPhuCap" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="PhuCap_NhanVien_PhuCap" Member="NhanVien_PhuCaps" ThisKey="id" OtherKey="idPhuCap" Type="NhanVien_PhuCap" />
    </Type>
  </Table>
  <Table Name="dbo.QuenMatKhau" Member="QuenMatKhaus">
    <Type Name="QuenMatKhau">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="taiKhoan" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="otp" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="thoiGianHetHan" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="daXacNhan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TaiKhoan_QuenMatKhau" Member="TaiKhoan1" ThisKey="taiKhoan" OtherKey="taiKhoan1" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="taiKhoan" Member="taiKhoan1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idNhanVien" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="matKhau" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="TaiKhoan_QuenMatKhau" Member="QuenMatKhaus" ThisKey="taiKhoan1" OtherKey="taiKhoan" Type="QuenMatKhau" />
      <Association Name="NhanVien_TaiKhoan" Member="NhanVien" ThisKey="idNhanVien" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThuongPhat" Member="ThuongPhats">
    <Type Name="ThuongPhat">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tienThuongPhat" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="loai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="lyDo" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="idNguoiTao" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="ThuongPhat_NhanVien_ThuongPhat" Member="NhanVien_ThuongPhats" ThisKey="id" OtherKey="idThuongPhat" Type="NhanVien_ThuongPhat" />
      <Association Name="NhanVien_ThuongPhat" Member="NhanVien" ThisKey="idNguoiTao" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TuyenDung" Member="TuyenDungs">
    <Type Name="TuyenDung">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tieuDe" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="idPhongBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idChucVu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idNguoiTao" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="xacThucYeuCau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="soLuongDuyet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ghiChuDuyet" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="ChucVu_TuyenDung" Member="ChucVu" ThisKey="idChucVu" OtherKey="id" Type="ChucVu" IsForeignKey="true" />
      <Association Name="NhanVien_TuyenDung" Member="NhanVien" ThisKey="idNguoiTao" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
      <Association Name="PhongBan_TuyenDung" Member="PhongBan" ThisKey="idPhongBan" OtherKey="id" Type="PhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NghiPhep" Member="NghiPheps">
    <Type Name="NghiPhep">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="LyDoNghi" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LoaiNghiPhep" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idNhanVien" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDanhGia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LoaiTruongHop" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="NhanVien_NghiPhep" Member="NhanVien" ThisKey="idNhanVien" OtherKey="id" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>